# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.3
loom_version=1.12-SNAPSHOT

# Mod Properties
mod_version=1.0.7+1.21.9
maven_group=se.icus.mag
archives_base_name=hotbar-switcher-reborn

# Dependencies
fabric_version=0.134.0+1.21.9
